org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


minecraft_version=26.1.2

minecraft_version_range=[26.1.2]

neo_version=26.1.2.31-beta
neo_version_range=[26.1.2.31-beta,)

mod_id=artifactscrafting
mod_name=Artifacts Crafting
mod_license=All Rights Reserved
mod_version=2.0.0-26.1.2
mod_group_id=net.mett3z.artifactscrafting
